apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overlord
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:                                          # new field
    - repoURL: https://github.com/vRaccoon/argo.git
      targetRevision: main
      path: ./apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

