apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: my-pvc
    namespace: nginx-argo
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi